export const pl = {
  appName: 'Pakownik',
  tagline: 'Spakuj się bez stresu',
  auth: {
    welcomeTitle: 'Pakuj mądrzej',
    welcomeSubtitle:
      'Listy pakowania dla całej rodziny. Zaloguj się, aby zarządzać listami i profilami członków.',
    login: 'Zaloguj się',
    register: 'Załóż konto',
    email: 'E-mail',
    password: 'Hasło',
    confirmPassword: 'Powtórz hasło',
    passwordMismatch: 'Hasła nie są identyczne',
    invalidCredentials: 'Nieprawidłowy e-mail lub hasło',
    emailExists: 'Konto z tym adresem e-mail już istnieje',
    invalidEmail: 'Podaj poprawny adres e-mail',
    noAccount: 'Nie masz konta?',
    hasAccount: 'Masz już konto?',
    logout: 'Wyloguj',
  },
  lists: {
    title: 'Moje listy',
    new: 'Nowa lista',
    empty: 'Nie masz jeszcze żadnych list pakowania.',
    delete: 'Usuń listę',
    deleteConfirm: 'Czy na pewno chcesz usunąć tę listę?',
    share: 'Udostępnij',
    shareEmail: 'Adres e-mail odbiorcy',
    shareEmailPlaceholder: 'np. partner@example.com',
    sharePermission: 'Uprawnienia',
    shareAdd: 'Udostępnij',
    shareRevoke: 'Cofnij dostęp',
    shareList: 'Udostępnione dla',
    sharedBadge: 'Udostępniona',
    sharedFrom: 'Od',
    sharedReadonly: 'Ta lista jest tylko do odczytu.',
    addItem: 'Dodaj pozycję',
    addMembers: 'Dodaj członków',
    pickMemberItemsTitle: 'Rzeczy do dopisania',
    pickMemberItemsHint: 'Odznacz te, które nie są potrzebne na ten wyjazd.',
    pickMemberItemsConfirm: 'Dopisz do listy',
    pickMemberItemsFor: 'dla',
    progress: 'Postęp pakowania',
    packed: 'Spakowane',
    of: 'z',
    pieces: 'szt.',
    items: 'pozycji',
    copied: 'Link skopiowany',
  },
  legal: {
    acceptTerms: 'Akceptuję',
    and: 'oraz',
    terms: 'Regulamin',
    privacy: 'Politykę prywatności',
    rodo: 'Klauzulę informacyjną RODO',
    termsRequired: 'Zaakceptuj regulamin, aby kontynuować',
  },
  family: {
    title: 'Rodzina',
    add: 'Dodaj członka',
    empty: 'Dodaj członków rodziny, aby przypisywać im rzeczy do pakowania.',
    addItem: 'Dodaj rzecz',
    deleteMember: 'Usuń członka',
    deleteMemberConfirm: 'Usunąć członka wraz z przypisanymi rzeczami?',
    share: 'Udostępnij',
    shareEmail: 'Adres e-mail odbiorcy',
    shareEmailPlaceholder: 'np. partner@example.com',
    shareSelectMembers: 'Wybierz członków',
    shareAdd: 'Udostępnij',
    shareRevoke: 'Cofnij dostęp',
    shareList: 'Udostępnione profile',
    sharedBadge: 'Udostępniony',
    sharedFrom: 'Od',
    sharedReadonly: 'Ten profil jest tylko do odczytu.',
  },
  form: {
    name: 'Nazwa',
    category: 'Kategoria',
    quantity: 'Ilość',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    itemSuggestionsHint: 'Zacznij wpisywać nazwę — podpowiemy rzeczy z innych profili rodziny.',
  },
  common: {
    loading: 'Ładowanie...',
    error: 'Wystąpił błąd',
    back: 'Wróć',
  },
};
