export const pl = {
  appName: 'Pakownik',
  tagline: 'Spakuj się bez stresu',
  auth: {
    welcomeTitle: 'Pakuj mądrzej',
    welcomeSubtitle:
      'Listy pakowania dla całej rodziny. Zaloguj się, aby zarządzać listami i profilami członków.',
    login: 'Zaloguj się',
    register: 'Załóż konto',
    email: 'E-mail',
    password: 'Hasło',
    confirmPassword: 'Powtórz hasło',
    passwordMismatch: 'Hasła nie są identyczne',
    noAccount: 'Nie masz konta?',
    hasAccount: 'Masz już konto?',
    logout: 'Wyloguj',
  },
  lists: {
    title: 'Moje listy',
    new: 'Nowa lista',
    empty: 'Nie masz jeszcze żadnych list pakowania.',
    delete: 'Usuń listę',
    deleteConfirm: 'Czy na pewno chcesz usunąć tę listę?',
    share: 'Udostępnij',
    shareLink: 'Link do udostępnienia',
    sharePermission: 'Uprawnienia',
    addItem: 'Dodaj pozycję',
    addMembers: 'Dodaj członków',
    progress: 'Postęp pakowania',
    packed: 'Spakowane',
    of: 'z',
    pieces: 'szt.',
    items: 'pozycji',
    copied: 'Link skopiowany',
  },
  family: {
    title: 'Rodzina',
    add: 'Dodaj członka',
    empty: 'Dodaj członków rodziny, aby przypisywać im rzeczy do pakowania.',
    addItem: 'Dodaj rzecz',
    deleteMember: 'Usuń członka',
    deleteMemberConfirm: 'Usunąć członka wraz z przypisanymi rzeczami?',
  },
  form: {
    name: 'Nazwa',
    category: 'Kategoria',
    quantity: 'Ilość',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
  },
  common: {
    loading: 'Ładowanie...',
    error: 'Wystąpił błąd',
    back: 'Wróć',
  },
};
